# Generated by Django 5.0.2 on 2024-03-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('equipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('nroSocios', models.IntegerField()),
                ('fechaFundacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Futbolista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('equipo', models.CharField(max_length=50)),
                ('dorsal', models.IntegerField()),
            ],
        ),
    ]
