# Generated by Django 5.0.2 on 2024-03-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenador',
            name='equipo',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='nacionalidad',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='nombreCompleto',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='pais',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='futbolista',
            name='equipo',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='futbolista',
            name='nacionalidad',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='futbolista',
            name='nombreCompleto',
            field=models.CharField(max_length=60),
        ),
    ]
